stages:
  - validate
  - deploy_tools
  - docker_push
  - release

before_script:
  - export CWD=$PWD
  - export DEPLOY_PATH=/home/gitlab-runner/deploy-tools-v2
  - export CI_COMMIT_TAG=${CI_COMMIT_TAG}

code_lint:
  stage: validate
  script:
    - npm install
    - npm run lint
  tags:
    - shell-runner
  except:
    - tags
    - master

pull_deploy_tools:
  stage: deploy_tools
  script:
    - cd $DEPLOY_PATH
    - git pull
  only:
    - develop
    - master
  tags:
    - shell-runner

docker_push:
  stage: docker_push
  script:
    - cd $DEPLOY_PATH
    - ./build-push.sh $CWD $CI_COMMIT_TAG
  tags:
    - shell-runner
  only:
    - develop
    - master

deploy_dev:
  stage: release
  script:
    - cd $DEPLOY_PATH
    - ./deploy-core.sh nexts-dev develop $CWD 
  only:
    - develop
  tags:
    - shell-runner

deploy_staging:
  stage: release
  script:
    - cd $DEPLOY_PATH
    - ./deploy-core.sh nexts-dev production $CWD 
  only:
    - master
  tags:
    - shell-runner


