const MerchantsCode = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  CODE_TAX_NO: 'CODE_TAX_NO',
  NOT_ID: 'NOT_ID',
  NOT_USERNAME: 'NOT_USERNAME',
  VERIFY_MERCHANT: 'VERIFY_MERCHANT',
  NOT_MERCHANT: 'NOT_MERCHANT',
  NOT_DELETE_MERCHANT: 'NOT_DELETE_MERCHANT',
  WRONG_PARAMS: 'WRONG_PARAMS',
};

export default MerchantsCode;
